[versions]
activity-ktx = "1.8.2"
agp = "8.4.0-alpha01"
androidx-core-ktx = "1.10.0"
annotation = "1.7.1"
appcompat = "1.6.1"
appcompat-resources = "1.6.1"
coil-compose = "2.5.0"
commons-codec = "1.16.0"
constraintlayout = "2.1.4"
converter-gson = "2.9.0"
core = "3.5.2"
core-ktx = "1.12.0"
core-runtime = "2.2.0"
core-splashscreen = "1.0.1"
datastore-preferences = "1.0.0"
dokka-base = "1.9.10"
exifinterface = "1.3.7"
fastjson2 = "2.0.44.android4"
fragment-ktx = "1.6.2"
gradle = "8.2.0"
gson = "2.10.1"
jackson-databind = "2.16.1"
jetbrains-kotlin-gradle-plugin = "1.9.22"
kotlin = "1.9.10"
kotlin-gradle-plugin = "1.9.22"
kotlin-reflect = "1.9.22"
kotlinx-coroutines-android = "1.7.3"
kotlinx-coroutines-core = "1.7.3"
kotlinx-datetime = "0.5.0"
kotlinx-serialization-json = "1.6.2"
ksp = "1.9.22-1.0.16"
lifecycle-livedata-core-ktx = "2.6.2"
lifecycle-livedata-ktx = "2.6.2"
lifecycle-runtime-ktx = "2.6.2"
lifecycle-viewmodel-ktx = "2.6.2"
material = "1.12.0-alpha02"
material3 = "1.2.0-beta01"
monitor = "1.6.1"
okhttp = "4.12.0"
paging-runtime = "3.2.1"
recyclerview = "1.3.2"
retrofit = "2.9.0"
runtime-livedata = "1.5.4"
security-crypto = "1.1.0-alpha06"
androidx-startup = "1.1.1"
ui = "1.5.4"
vastcore = "0.0.7"
vastnetstatelayout = "0.0.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-ktx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "converter-gson" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat-resources" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
core = { module = "com.google.zxing:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "core-runtime" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka-base" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-v1810 = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin-gradle-plugin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-reflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines-android" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "lifecycle-livedata-core-ktx" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-livedata-core-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-runtime" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtime-livedata" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
vastcore = { module = "io.github.sakurajimamaii:VastCore", version.ref = "vastcore" }
vastnetstatelayout = { module = "io.github.sakurajimamaii:VastNetStateLayout", version.ref = "vastnetstatelayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = {id= "com.google.devtools.ksp",version.ref = "ksp"}